<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="4" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22571" started-at="2022-08-25T10:22:21 IST" finished-at="2022-08-25T10:22:43 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22571" started-at="2022-08-25T10:22:21 IST" finished-at="2022-08-25T10:22:43 IST">
      <class name="TestScript.VerifyOnlineAdmissionSystem">
        <test-method status="PASS" signature="configBS()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configBS" is-config="true" duration-ms="15" started-at="2022-08-25T10:22:21 IST" finished-at="2022-08-25T10:22:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBS -->
        <test-method status="PASS" signature="configBC()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configBC" is-config="true" duration-ms="4870" started-at="2022-08-25T10:22:21 IST" finished-at="2022-08-25T10:22:25 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBC -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configBM" is-config="true" duration-ms="6200" started-at="2022-08-25T10:22:26 IST" finished-at="2022-08-25T10:22:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="SKIP" signature="verifyapplicationForm()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="verifyapplicationForm" duration-ms="30" retried="true" started-at="2022-08-25T10:22:32 IST" finished-at="2022-08-25T10:22:32 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestScript.VerifyOnlineAdmissionSystem.verifyapplicationForm(VerifyOnlineAdmissionSystem.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyapplicationForm -->
        <test-method status="PASS" signature="configAM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configAM" is-config="true" duration-ms="0" started-at="2022-08-25T10:22:32 IST" finished-at="2022-08-25T10:22:32 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configBM" is-config="true" duration-ms="2257" started-at="2022-08-25T10:22:32 IST" finished-at="2022-08-25T10:22:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="SKIP" signature="verifyapplicationForm()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="verifyapplicationForm" duration-ms="13" retried="true" started-at="2022-08-25T10:22:34 IST" finished-at="2022-08-25T10:22:34 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestScript.VerifyOnlineAdmissionSystem.verifyapplicationForm(VerifyOnlineAdmissionSystem.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyapplicationForm -->
        <test-method status="PASS" signature="configAM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configAM" is-config="true" duration-ms="1" started-at="2022-08-25T10:22:34 IST" finished-at="2022-08-25T10:22:34 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configBM" is-config="true" duration-ms="2340" started-at="2022-08-25T10:22:34 IST" finished-at="2022-08-25T10:22:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="SKIP" signature="verifyapplicationForm()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="verifyapplicationForm" duration-ms="4" retried="true" started-at="2022-08-25T10:22:36 IST" finished-at="2022-08-25T10:22:36 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestScript.VerifyOnlineAdmissionSystem.verifyapplicationForm(VerifyOnlineAdmissionSystem.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyapplicationForm -->
        <test-method status="PASS" signature="configAM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configAM" is-config="true" duration-ms="3" started-at="2022-08-25T10:22:36 IST" finished-at="2022-08-25T10:22:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configBM" is-config="true" duration-ms="2590" started-at="2022-08-25T10:22:36 IST" finished-at="2022-08-25T10:22:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="SKIP" signature="verifyapplicationForm()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="verifyapplicationForm" duration-ms="8" retried="true" started-at="2022-08-25T10:22:39 IST" finished-at="2022-08-25T10:22:39 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestScript.VerifyOnlineAdmissionSystem.verifyapplicationForm(VerifyOnlineAdmissionSystem.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyapplicationForm -->
        <test-method status="PASS" signature="configAM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configAM" is-config="true" duration-ms="0" started-at="2022-08-25T10:22:39 IST" finished-at="2022-08-25T10:22:39 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method status="PASS" signature="configBM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configBM" is-config="true" duration-ms="2807" started-at="2022-08-25T10:22:39 IST" finished-at="2022-08-25T10:22:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBM -->
        <test-method status="FAIL" signature="verifyapplicationForm()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="verifyapplicationForm" duration-ms="4" started-at="2022-08-25T10:22:42 IST" finished-at="2022-08-25T10:22:42 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at TestScript.VerifyOnlineAdmissionSystem.verifyapplicationForm(VerifyOnlineAdmissionSystem.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyapplicationForm -->
        <test-method status="PASS" signature="configAM()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configAM" is-config="true" duration-ms="0" started-at="2022-08-25T10:22:42 IST" finished-at="2022-08-25T10:22:42 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAM -->
        <test-method status="PASS" signature="configAC()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configAC" is-config="true" duration-ms="855" started-at="2022-08-25T10:22:42 IST" finished-at="2022-08-25T10:22:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAC -->
        <test-method status="PASS" signature="configAS()[pri:0, instance:TestScript.VerifyOnlineAdmissionSystem@462d5aee]" name="configAS" is-config="true" duration-ms="1" started-at="2022-08-25T10:22:43 IST" finished-at="2022-08-25T10:22:43 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAS -->
      </class> <!-- TestScript.VerifyOnlineAdmissionSystem -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
